name: "XServerDeploy"

on:
  workflow_dispatch:

jobs:
  deploy-to-xserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      ## FTP deployを使用したFTPアップロードの記述
      - name: Upload files on Xserver
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        ## step2でGitHub secretsに登録した認証情報をここで呼び出します
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /
          ## exclude を指定するとデフォルト除外（.git*/node_modules）も上書きされるため再指定している
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            docs/**
            README.md
            CHANGELOG.md
